version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    # volumes:
    #   - ./upload:/usr/src/app/upload
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    volumes:
      - ./data:/data/db
      - ./init-mongo-user.js:/docker-entrypoint-initdb.d/init-mongo-user.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}

